// Style Dictionary v4 build for swapl tokens.
// Emits TS (web), Swift (iOS), Kotlin (Android) from one set of JSON sources.
// Run: `node build.mjs` (no install needed if peer style-dictionary is present;
// otherwise this file is the canonical reference for the codegen contract).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

let StyleDictionary;
try {
  StyleDictionary = (await import("style-dictionary")).default;
} catch {
  console.error("style-dictionary not installed. Run: pnpm install");
  process.exit(1);
}

// ---------- formatters ----------

StyleDictionary.registerFormat({
  name: "swapl/swift",
  format: ({ dictionary }) => {
    const lines = [
      "// Auto-generated by @swapl/design-tokens. Do not edit by hand.",
      "import SwiftUI",
      "",
      "public extension Color {",
      "  init(hex: String) {",
      "    var v: UInt64 = 0",
      "    Scanner(string: hex.replacingOccurrences(of: \"#\", with: \"\")).scanHexInt64(&v)",
      "    self.init(",
      "      .sRGB,",
      "      red:   Double((v >> 16) & 0xFF) / 255.0,",
      "      green: Double((v >> 8) & 0xFF) / 255.0,",
      "      blue:  Double(v & 0xFF) / 255.0,",
      "      opacity: 1",
      "    )",
      "  }",
      "}",
      "",
      "public enum SwaplColor {",
    ];
    dictionary.allTokens
      .filter((t) => t.attributes?.category === "color" || t.path[0] === "color")
      .forEach((t) => {
        const id = t.path.slice(1).map(camel).join("");
        lines.push(`  public static let ${id} = Color(hex: "${t.value}")`);
      });
    lines.push("}", "");

    lines.push("public enum SwaplSemanticLight {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "semantic" && t.path[1] === "light")
      .forEach((t) => {
        const id = t.path.slice(2).map(camel).join("");
        lines.push(`  public static let ${id} = Color(hex: "${t.value}")`);
      });
    lines.push("}", "");

    lines.push("public enum SwaplSemanticDark {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "semantic" && t.path[1] === "dark")
      .forEach((t) => {
        const id = t.path.slice(2).map(camel).join("");
        lines.push(`  public static let ${id} = Color(hex: "${t.value}")`);
      });
    lines.push("}", "");

    // City palettes as a struct keyed by palette name.
    lines.push("public struct SwaplCityPalette {");
    lines.push("  public let sky: Color");
    lines.push("  public let building: Color");
    lines.push("  public let roof: Color");
    lines.push("  public let window: Color");
    lines.push("  public let accent: Color");
    lines.push("}", "");
    lines.push("public enum SwaplCityPalettes {");
    const palettes = new Set(
      dictionary.allTokens
        .filter((t) => t.path[0] === "city")
        .map((t) => t.path[1])
    );
    palettes.forEach((p) => {
      const get = (slot) =>
        dictionary.allTokens.find(
          (t) => t.path[0] === "city" && t.path[1] === p && t.path[2] === slot
        )?.value ?? "#000000";
      lines.push(
        `  public static let ${p} = SwaplCityPalette(`,
        `    sky:      Color(hex: "${get("sky")}"),`,
        `    building: Color(hex: "${get("building")}"),`,
        `    roof:     Color(hex: "${get("roof")}"),`,
        `    window:   Color(hex: "${get("window")}"),`,
        `    accent:   Color(hex: "${get("accent")}")`,
        "  )"
      );
    });
    lines.push("}", "");

    lines.push("public enum SwaplRadius {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "radius")
      .forEach((t) => {
        const id = camel(t.path[1]);
        lines.push(`  public static let ${id}: CGFloat = ${t.value}`);
      });
    lines.push("}", "");

    lines.push("public enum SwaplSpacing {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "spacing")
      .forEach((t) => {
        lines.push(`  public static let s${t.path[1]}: CGFloat = ${t.value}`);
      });
    lines.push("}", "");

    lines.push("public enum SwaplFontFamily {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "font" && t.path[1] === "family")
      .forEach((t) => {
        lines.push(`  public static let ${t.path[2]} = "${t.value}"`);
      });
    lines.push("}", "");
    return lines.join("\n");
  },
});

StyleDictionary.registerFormat({
  name: "swapl/kotlin",
  format: ({ dictionary }) => {
    const lines = [
      "// Auto-generated by @swapl/design-tokens. Do not edit by hand.",
      "package app.swapl.designtokens",
      "",
      "import androidx.compose.ui.graphics.Color",
      "import androidx.compose.ui.unit.dp",
      "",
      "private fun hex(s: String): Color {",
      "  val v = s.removePrefix(\"#\").toLong(16)",
      "  return Color(red = ((v shr 16) and 0xFF).toInt(), green = ((v shr 8) and 0xFF).toInt(), blue = (v and 0xFF).toInt())",
      "}",
      "",
      "object SwaplColors {",
    ];
    dictionary.allTokens
      .filter((t) => t.path[0] === "color")
      .forEach((t) => {
        const id = pascal(t.path.slice(1).join("-"));
        lines.push(`  val ${id} = hex("${t.value}")`);
      });
    lines.push("}", "");

    lines.push("object SwaplSemanticLight {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "semantic" && t.path[1] === "light")
      .forEach((t) => {
        const id = pascal(t.path.slice(2).join("-"));
        lines.push(`  val ${id} = hex("${t.value}")`);
      });
    lines.push("}", "");

    lines.push("object SwaplSemanticDark {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "semantic" && t.path[1] === "dark")
      .forEach((t) => {
        const id = pascal(t.path.slice(2).join("-"));
        lines.push(`  val ${id} = hex("${t.value}")`);
      });
    lines.push("}", "");

    lines.push("data class SwaplCityPalette(val sky: Color, val building: Color, val roof: Color, val window: Color, val accent: Color)");
    lines.push("");
    lines.push("object SwaplCityPalettes {");
    const palettes = new Set(
      dictionary.allTokens
        .filter((t) => t.path[0] === "city")
        .map((t) => t.path[1])
    );
    palettes.forEach((p) => {
      const get = (slot) =>
        dictionary.allTokens.find(
          (t) => t.path[0] === "city" && t.path[1] === p && t.path[2] === slot
        )?.value ?? "#000000";
      lines.push(`  val ${pascal(p)} = SwaplCityPalette(`);
      lines.push(`    sky = hex("${get("sky")}"),`);
      lines.push(`    building = hex("${get("building")}"),`);
      lines.push(`    roof = hex("${get("roof")}"),`);
      lines.push(`    window = hex("${get("window")}"),`);
      lines.push(`    accent = hex("${get("accent")}"))`);
    });
    lines.push("  fun forName(name: String): SwaplCityPalette = when (name.lowercase()) {");
    palettes.forEach((p) => {
      lines.push(`    "${p}" -> ${pascal(p)}`);
    });
    lines.push("    else -> Warm");
    lines.push("  }");
    lines.push("}", "");

    lines.push("object SwaplRadius {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "radius")
      .forEach((t) => {
        const id = camel(t.path[1]);
        lines.push(`  val ${id} = ${t.value}.dp`);
      });
    lines.push("}", "");

    lines.push("object SwaplSpacing {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "spacing")
      .forEach((t) => {
        lines.push(`  val s${t.path[1]} = ${t.value}.dp`);
      });
    lines.push("}", "");

    lines.push("object SwaplFontFamily {");
    dictionary.allTokens
      .filter((t) => t.path[0] === "font" && t.path[1] === "family")
      .forEach((t) => {
        lines.push(`  const val ${t.path[2]} = "${t.value}"`);
      });
    lines.push("}", "");
    return lines.join("\n");
  },
});

StyleDictionary.registerFormat({
  name: "swapl/ts",
  format: ({ dictionary }) => {
    // Flat object grouped by category for use from web (TS) and as docs.
    const out = { color: {}, semantic: { light: {}, dark: {} }, city: {}, radius: {}, spacing: {}, font: { family: {}, weight: {} } };
    dictionary.allTokens.forEach((t) => {
      let cur = out;
      const last = t.path.at(-1);
      for (const seg of t.path.slice(0, -1)) {
        cur[seg] = cur[seg] ?? {};
        cur = cur[seg];
      }
      cur[last] = t.value;
    });
    return [
      "// Auto-generated by @swapl/design-tokens. Do not edit by hand.",
      `export const tokens = ${JSON.stringify(out, null, 2)} as const;`,
      "export type Tokens = typeof tokens;",
      "",
    ].join("\n");
  },
});

// ---------- helpers ----------

function camel(s) {
  return s.replace(/[-_]([a-z0-9])/g, (_, c) => c.toUpperCase());
}
function pascal(s) {
  const c = camel(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

// ---------- run ----------

const buildDir = path.join(__dirname, "build");
fs.rmSync(buildDir, { recursive: true, force: true });
fs.mkdirSync(buildDir, { recursive: true });

const sd = new StyleDictionary({
  source: [path.join(__dirname, "tokens/**/*.json")],
  platforms: {
    ts: {
      transformGroup: "js",
      buildPath: "build/ts/",
      files: [{ destination: "index.ts", format: "swapl/ts" }],
    },
    swift: {
      transformGroup: "ios-swift",
      buildPath: "build/swift/",
      files: [{ destination: "SwaplTokens.swift", format: "swapl/swift" }],
    },
    kotlin: {
      transformGroup: "android",
      buildPath: "build/kotlin/",
      files: [{ destination: "SwaplTokens.kt", format: "swapl/kotlin" }],
    },
  },
});

await sd.buildAllPlatforms();
console.log("✓ swapl design tokens built → build/ts, build/swift, build/kotlin");
