// Auto-generated by @swapl/design-tokens. Do not edit by hand.
// Source: packages/design-tokens/tokens/**/*.json — regenerate via `pnpm --filter @swapl/design-tokens build`.

package app.swapl.designtokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

private fun hex(s: String): Color {
    val v = s.removePrefix("#").toLong(16)
    return Color(
        red = ((v shr 16) and 0xFF).toInt(),
        green = ((v shr 8) and 0xFF).toInt(),
        blue = (v and 0xFF).toInt(),
    )
}

object SwaplColors {
    val Cream = hex("#FAF6E8")
    val Cream2 = hex("#F5EFD9")
    val Navy = hex("#1A1F3C")
    val Navy2 = hex("#2A3066")
    val Navy3 = hex("#5E63A0")
    val Pink = hex("#F24B8E")
    val PinkLight = hex("#FDEEF5")
    val CardBg = hex("#FFFFFF")
    val Line = hex("#E5E0D0")
    val TagBg = hex("#F0EBD8")
    val White = hex("#FFFFFF")
    val NavyDark = hex("#11142A")
}

object SwaplSemanticLight {
    val Background = hex("#FAF6E8")
    val Foreground = hex("#1A1F3C")
    val Card = hex("#FFFFFF")
    val CardForeground = hex("#1A1F3C")
    val Primary = hex("#F24B8E")
    val PrimaryForeground = hex("#FFFFFF")
    val Secondary = hex("#F0EBD8")
    val SecondaryForeground = hex("#1A1F3C")
    val Muted = hex("#F5EFD9")
    val MutedForeground = hex("#5E63A0")
    val Accent = hex("#FDEEF5")
    val AccentForeground = hex("#1A1F3C")
    val Border = hex("#E5E0D0")
    val Input = hex("#E5E0D0")
    val Ring = hex("#F24B8E")
    val Destructive = hex("#DC2626")
}

object SwaplSemanticDark {
    val Background = hex("#11142A")
    val Foreground = hex("#FAF6E8")
    val Card = hex("#1A1F3C")
    val CardForeground = hex("#FAF6E8")
    val Primary = hex("#F24B8E")
    val PrimaryForeground = hex("#FFFFFF")
    val Secondary = hex("#2A3066")
    val SecondaryForeground = hex("#FAF6E8")
    val Muted = hex("#2A3066")
    val MutedForeground = hex("#A0A4C8")
    val Accent = hex("#2A3066")
    val AccentForeground = hex("#FAF6E8")
    val Border = hex("#2A2F4D")
    val Input = hex("#3A3F5D")
    val Ring = hex("#F24B8E")
    val Destructive = hex("#F87171")
}

data class SwaplCityPalette(
    val sky: Color,
    val building: Color,
    val roof: Color,
    val window: Color,
    val accent: Color,
)

object SwaplCityPalettes {
    val Warm = SwaplCityPalette(hex("#F5D9B5"), hex("#C2410C"), hex("#7C2D12"), hex("#FED7AA"), hex("#FDBA74"))
    val Cool = SwaplCityPalette(hex("#DBEAFE"), hex("#1E3A8A"), hex("#1E293B"), hex("#BFDBFE"), hex("#93C5FD"))
    val Rose = SwaplCityPalette(hex("#FCE7F3"), hex("#9D174D"), hex("#500724"), hex("#FBCFE8"), hex("#F9A8D4"))
    val Sage = SwaplCityPalette(hex("#D1FAE5"), hex("#065F46"), hex("#064E3B"), hex("#A7F3D0"), hex("#6EE7B7"))
    val Dusk = SwaplCityPalette(hex("#E0E7FF"), hex("#3730A3"), hex("#1E1B4B"), hex("#C7D2FE"), hex("#A5B4FC"))
    val Sand = SwaplCityPalette(hex("#FEF3C7"), hex("#92400E"), hex("#451A03"), hex("#FDE68A"), hex("#FCD34D"))
    val Mono = SwaplCityPalette(hex("#E5E5E2"), hex("#1C1A17"), hex("#0A0A09"), hex("#FAF6E8"), hex("#999999"))

    fun forName(name: String): SwaplCityPalette = when (name.lowercase()) {
        "warm" -> Warm
        "cool" -> Cool
        "rose" -> Rose
        "sage" -> Sage
        "dusk" -> Dusk
        "sand" -> Sand
        "mono" -> Mono
        else -> Warm
    }
}

object SwaplRadius {
    val sm = 8.4.dp
    val md = 11.2.dp
    val lg = 14.dp
    val xl = 19.6.dp
    val xl2 = 25.2.dp
    val pill = 9999.dp
}

object SwaplSpacing {
    val s1 = 4.dp
    val s2 = 8.dp
    val s3 = 12.dp
    val s4 = 16.dp
    val s5 = 20.dp
    val s6 = 24.dp
    val s8 = 32.dp
    val s10 = 40.dp
    val s12 = 48.dp
    val s16 = 64.dp
}

object SwaplFontFamily {
    const val Display = "Fraunces"
    const val Body = "Inter"
    const val Mono = "JetBrainsMono"
}
